# Nord Color Palette
$nord0 = rgba(2e3440ff)   #2e3440
$nord1 = rgba(3b4252ff)   #3b4252
$nord2 = rgba(434c5eff)   #434c5e
$nord3 = rgba(4c566aff)   #4c566a
$nord4 = rgba(d8dee9ff)   #d8dee9
$nord5 = rgba(e5e9f0ff)   #e5e9f0
$nord6 = rgba(eceff4ff)   #eceff4
$nord7 = rgba(8fbcbbff)   #8fbcbb
$nord8 = rgba(88c0d0ff)   #88c0d0
$nord9 = rgba(81a1c1ff)   #81a1c1
$nord10 = rgba(5e81acff)  #5e81ac
$nord11 = rgba(bf616aff)  #bf616a
$nord12 = rgba(d08770ff)  #d08770
$nord13 = rgba(ebcb8bff)  #ebcb8b
$nord14 = rgba(a3be8cff)  #a3be8c
$nord15 = rgba(b48eadff)  #b48ead

$black = $nord0
$gray = $nord2
$offwhite = $nord4
$white = $nord5
$teal = $nord7
$cyan = $nord8
$blue = $nord10
$red = $nord11
$yellow = $nord13
$green = $nord14
$magenta = $nord15

$background = $nord0
$surface = $nord1
$shadow = $nord1
$comments = $nord3
$border = $nord3
$border_inactive = $border
$border_active = $cyan
$border_inactive_dim = rgba(4c566a44)
$shadow_color = rgba(2e3440dd)

$text = $nord5

$error = $red
$warning = $yellow
$success = $green
$special = $magenta

$calm = $teal
$accent = $cyan
$tertiary = $blue
