general {
  gaps_in = 2
  gaps_out = 5
  border_size = 2
  col.active_border = rgba(88c0d0ff) rgba(a3be8cff) 45deg
  col.inactive_border = rgba(434c5eaa)
  layout = master
}

windowrulev2 = float, title:^(btop|nnn|todo)$
windowrulev2 = size 80% 80%, title:^(btop|nnn|todo)$
windowrulev2 = center, title:^(btop|nnn|todo)$

windowrulev2 = float, class:^FortiClient$
windowrulev2 = float, class:^Vncviewer$

windowrulev2 = float, title:^Volume Control$
windowrulev2 = size 50% 50%, title:^Volume Control$

# E.g. popup window for saving files in browser such as Firefox
windowrulev2 = float, title:^(Save As).*$
windowrulev2 = size 80% 80%, title:^(Save As).*$
windowrulev2 = center,title:^(Save As).*$

windowrulev2 = workspace 3, class:(Slack)

windowrulev2 = float, class:(qemu)
windowrulev2 = size 90% 90%, class:(qemu)
windowrulev2 = center, class:(qemu)
windowrulev2 = workspace 4, class:(qemu)
